"""Rule evidence tool: reads TRAIN-split data only and writes docs/RULES.md.

For every rule it reports how many TRAIN plates satisfy its conditions
(after symptoms are derived), and the precision (share of those plates whose
true class equals the rule's conclusion) and recall for the concluded fault.
Use it to write/revise rules; never feed it the test split.
"""
import os
import sys

from data_loader import CLASSES, FEATURES, banner, load_dataset, stratified_split
from inference import applicable, forward_chain
from kb import LEVELS, Thresholds
from rules import DERIVED, RULES


def distribution_table(train, thresholds):
    """Text table: for each feature and class, % of train plates LOW/MEDIUM/HIGH.
    O(n*F). This is the evidence used to choose rule conditions."""
    facts = [(p.label, thresholds.discretise(p.features)) for p in train]
    lines = ["%-22s" % "feature (L/M/H %)" + "".join("%-13s" % c[:12] for c in CLASSES)]
    for name in FEATURES:
        cells = []
        for cls in CLASSES:
            sub = [f[name] for lab, f in facts if lab == cls]
            cells.append("%2d/%2d/%2d".ljust(13) % tuple(round(100 * sub.count(v) / len(sub))
                                                         for v in LEVELS))
        lines.append("%-22s" % name[:21] + "".join(cells))
    return "\n".join(lines)


def rule_statistics(train, thresholds):
    """{rule id: (matches, per-class match counts)} over the train plates.
    Symptoms are derived with the forward chainer first. O(n*R*C)."""
    stats = {r.rid: [0, {c: 0 for c in CLASSES}] for r in RULES}
    for plate in train:
        facts = forward_chain(thresholds.discretise(plate.features)).facts
        for rule in RULES:
            if applicable(rule, facts):
                stats[rule.rid][0] += 1
                stats[rule.rid][1][plate.label] += 1
    return stats


def render_markdown(train, thresholds, source):
    """docs/RULES.md text: each rule with its measured TRAIN evidence."""
    sizes = {c: sum(1 for p in train if p.label == c) for c in CLASSES}
    stats = rule_statistics(train, thresholds)
    out = ["# Rule base and evidence", "", "> " + banner_text(source), "",
           "Generated by `python3 rule_evidence.py` from the TRAIN split only "
           "(%d plates). Precision = share of matching train plates whose true class is "
           "the rule's conclusion; recall = share of that class's train plates matched." % len(train),
           "", "| id | pri | rule | conditions | matches | precision | recall | rationale |",
           "|----|-----|------|------------|---------|-----------|--------|-----------|"]
    for rule in RULES:
        n, per = stats[rule.rid]
        attr, value = rule.conclusion
        conds = " AND ".join("%s in {%s}" % (a, ",".join(sorted(v))) for a, v in rule.conditions) or "(always)"
        if attr == "fault":
            prec = "%.0f%%" % (100 * per[value] / n) if n else "n/a"
            rec = "%.0f%%" % (100 * per[value] / sizes[value])
        else:
            best = max(per, key=per.get) if n else "-"
            prec, rec = "(symptom; most common class: %s)" % best, "-"
        out.append("| %s | %d | %s | %s | %d | %s | %s | %s |"
                   % (rule.rid, rule.priority, rule.text, conds, n, prec, rec, rule.why))
    out += ["", "## Threshold table (train quantiles 25%/75%)", "", "```", thresholds.render(), "```",
            "", "## Class distribution of discretised features (train, % LOW/MEDIUM/HIGH)", "",
            "```", distribution_table(train, thresholds), "```"]
    return "\n".join(out) + "\n"


def banner_text(source):
    return ("DATA SOURCE: REAL UCI file." if source == "REAL" else
            "DATA SOURCE: *** SYNTHETIC DATA *** - evidence below describes the synthetic "
            "stand-in, NOT real steel plates. Re-run with data/Faults.NNA and revise the rules.")


if __name__ == "__main__":
    dataset = load_dataset(download=False)
    train, _ = stratified_split(dataset.plates, seed=42)
    th = Thresholds(train)
    print(banner(dataset))
    if "--write" in sys.argv:
        path = os.path.join("docs", "RULES.md")
        with open(path, "w") as handle:
            handle.write(render_markdown(train, th, dataset.source))
        print("wrote", path)
    else:
        print(distribution_table(train, th))
        for rid, (n, per) in rule_statistics(train, th).items():
            print(rid, n, {k: v for k, v in per.items() if v})
